apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  namespace: cp4na
  name: mq-qmgr-naccts01-nha-nosec
spec:
  license:
    accept: true
    license: L-RJON-BXUPZ2
    use: NonProduction
  pki:
    keys:
      - name: default
        secret:
          secretName: mq-naccts01-tls
          items: 
          - tls.key
          - tls.crt
  web:
    enabled: false
  version: 9.2.3.0-r1
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  queueManager:
    name: NACCTS01
    mqsc:
      - configMap:
          items:
            - mqsc
          name: mq-mqsc-naccts01-nosec
    availability:
      type: NativeHA
    storage:
      queueManager:
        type: persistent-claim

