apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mq-qmgr-naccts01-nha-nosec-ibm-mq-traffic
  namespace: cp4na
spec:
  host: naccts2e-svrconn.chl.mq.ibm.com
  to:
    kind: Service
    name: mq-qmgr-naccts01-nha-nosec-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
