kind: ConfigMap

apiVersion: v1

metadata:

  name: mq-mqsc-naccts01-sec-ldap

  namespace: mqpot

data:

  mqsc: |

    ALTER QMGR DEADQ('NACCTS.DLQ')

    DEFINE QLOCAL('DIANA.LQ.CMVPCH.KST0') 

    DEFINE QLOCAL('DIANA.LQ.CMVPCHPR.KST0')

    DEFINE QLOCAL('DIANA.LQ.FDSCORE.KST0') 

    DEFINE QLOCAL('DIANA.LQ.FDSCOREPR.KST0') 

    DEFINE QLOCAL('DIANA.LQ.IDSCORE.KST0') 

    DEFINE QLOCAL('NACCTS.DLQ') MAXDEPTH(10000) 

    DEFINE CHANNEL('DFQ1.NACCTSK1') CHLTYPE(RCVR) 

    DEFINE CHANNEL('NACCTS.SVRCONN') CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')

    SET CHLAUTH('NACCTS.SVRCONN') TYPE(BLOCKUSER) USERLIST('nobody') DESCR('Override for MQM') WARN(NO) ACTION(ADD)

    SET CHLAUTH('NACCTS.SVRCONN') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS) DESCR('Block All') WARN(NO) ACTION(ADD)

    SET CHLAUTH('NACCTS.SVRCONN') TYPE(USERMAP) CLNTUSER('naccpot') USERSRC(CHANNEL) DESCR('accept onlyt this userid') ACTION(ADD)

    DEFINE AUTHINFO(USE.LDAP) AUTHTYPE(IDPWLDAP) CONNAME('d-vds.rw.discoverfinancial.com(636)') LDAPUSER('uid=naccpot,ou=Apps,ou=Admin,o=DFSI') LDAPPWD('****') SECCOMM(YES) USRFIELD('uid') SHORTUSR('uid')BASEDNU('ou=Apps,ou=Admin,o=DFSI') AUTHORMD(SEARCHGRP) BASEDNG('ou=Apps,ou=Admin,o=DFSI') CLASSGRP('groupOfUniqueNames') FINDGRP('uniqueMember')  

    ALTER QMGR CONNAUTH(USE.LDAP)

    SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('naccpot') AUTHADD(CONNECT,INQ,DSP) 

    SET AUTHREC PROFILE('DIANA.LQ.CMVPCH.KST0') OBJTYPE(QUEUE) PRINCIPAL('naccpot') AUTHADD(PUT,GET,INQ,BROWSE)  

    REFRESH SECURITY
