kind: ConfigMap
apiVersion: v1
metadata:
  name: mq-mqsc-naccts01-nosec
  namespace: cp4na
data:
  mqsc: |
    ALTER QMGR DEADQ('NACCTS.DLQ')
    DEFINE QLOCAL('DIANA.LQ.CMVPCH.KST0') 
    DEFINE QLOCAL('DIANA.LQ.CMVPCHPR.KST0')
    DEFINE QLOCAL('DIANA.LQ.FDSCORE.KST0') 
    DEFINE QLOCAL('DIANA.LQ.FDSCOREPR.KST0') 
    DEFINE QLOCAL('DIANA.LQ.IDSCORE.KST0') 
    DEFINE QLOCAL('NACCTS.DLQ') MAXDEPTH(10000) 
    DEFINE CHANNEL('DFQ1.NACCTSK1') CHLTYPE(RCVR) 
    DEFINE CHANNEL('NACCTS.SVRCONN') CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12')
    SET CHLAUTH(NACCTS.SVRCONN) TYPE(BLOCKUSER) USERLIST(NOBODY)
    REFRESH SECURITY TYPE(CONNAUTH)
